# Generated by Django 5.1.5 on 2025-02-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationresult',
            name='input_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='insights',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='results',
            field=models.JSONField(default=dict),
        ),
        migrations.AddIndex(
            model_name='simulationresult',
            index=models.Index(fields=['-created_at'], name='ml_pipeline_created_00fe78_idx'),
        ),
    ]
