# Generated by Django 5.1.5 on 2025-02-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_pipeline', '0002_alter_simulationresult_input_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationresult',
            name='visualizations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='input_data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='insights',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='results',
            field=models.JSONField(),
        ),
    ]
